---
title: "Water Retaining Facilities Analysis"
author: 
  - "Name: Kabir Carpenter"
  - "Professor: Alexis Robinson"
date: "2024-07-13"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(rmarkdown)
setwd("D:/datascience/Spatial Data Science")
getwd()

```

```{r}

WaterRetaining = read.csv("WaterRetainingFacilities.csv", sep = ",", header = TRUE)
summary(WaterRetaining)

```





```{r}
# Histogram of ImpoundmentLevel
hist(WaterRetaining$ImpoundmentLevel, 
     main = "Histogram of ImpoundmentLevel", 
     xlab = "ImpoundmentLevel (mams)", 
     col = "blue")


```


```{r}
# Scatter plot of ImpoundmentLevel vs DamHeight
plot(WaterRetaining$DamHeight, WaterRetaining$ImpoundmentLevel,
     main = "ImpoundmentLevel vs DamHeight",
     xlab = "Dam Height (m)",
     ylab = "Impoundment Level (mams)",
     col = "red",
     pch = 19)

```


```{r}
# Calculate mean and weighted mean centre for ImpoundmentLevel
mean_impoundment = mean(WaterRetaining$ImpoundmentLevel, na.rm = TRUE)
weighted_mean_impoundment = sum(WaterRetaining$ImpoundmentLevel * WaterRetaining$StorageLevel, na.rm = TRUE) / sum(WaterRetaining$StorageLevel, na.rm = TRUE)

mean_impoundment
weighted_mean_impoundment

```











